# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tonyai',
                'doc_host': 'https://AntonReborn.github.io',
                'git_url': 'https://github.com/AntonReborn/tonyai',
                'lib_path': 'tonyai'},
  'syms': {'tonyai.core': {'tonyai.core.foo': ('core.html#foo', 'tonyai/core.py')}}}
